### ISSUE TITLE
Progressive rendering of <style> elements per component

### ISSUE THREAD

**Issue by TxHawks** [robinweser/fela#337]
**Environment**: Server
**Type**: Feature

-------------------
#### Description
Over at the Styletron repo, @jakearchibald  [asked](https://github.com/rtsao/styletron/issues/137) about the possibility of outputting a `<style>` element just before each component, containing the additional not-already-output classes for that component. [Here is a writeup](https://jakearchibald.com/2016/link-in-body/) of his on why it can be a good idea.

I think it can be a very useful feature for Fela as well.

**Edited to add:**
#### Proposal
Allow Fela to generate a `<style>` tag for each individual component, but only include declerations that have not already been included in `<style>` tags generated by components rendered before. Such behavior can enable the browser to progressively render the page, component by component. 

Such an approach can be seen as an enhancement of the critical CSS approach.

**Code Example**:
```javascript
import React from 'react';
import { render } from 'react-dom';
import { createRenderer } from 'fela';
import { Provider, createComponent } from 'react-fela';


const renderer = createRenderer();

const headingStyles = () => ({
  color: '#333',
  fontSize: '36px'
});

const textStyles = () => ({
   color: '#333',
  fontSize: '16px'
});

const Title = createComponent(headingStyles, 'h1');
const Text = createComponent(textStyles, 'p');

const Components = () => (
  <div>
    <Title>
      Example title
    </Title>
    <Text>
      Example paragraph
    </Text>
  </div>
);

render(
  <Provider renderer={renderer}>
    <Components />
  </Provider>,
  document.getElementById('app')
);
```

Should be rendered to:
```html
<div id="app">
  <style  type="text/css">
    .a {color:#333}
    .b {font-size:36px}
  </style>
  <h1 class="a b">Example Title</h1>
  <style  type="text/css">
    .c {font-size:16px}
  </style>
  <p class="a c">Example paragraph</p>
</div>
```

**Comment by rofrischmann** [comment]
Hmm. I don't think that makes any sense with Atomic CSS Design as styles are not "bound" to a component but rather globally reused. Or do I missunderstand something? They're probably talking about adding a new <style> for every component right?

**Comment by TxHawks** [comment]
CCing @jakearchibald (forgot to do it initially) 
Yes, the idea is to generate a `<style>` tag for every component, but only add classes that have not already been generated by other components. 

This can enable the browser to progressively render the page, component by component. I think at can be seen as an enhancement of the critical CSS approach.

**Comment by rofrischmann** [comment]
Yeah fine, now I totally understand that. Could you perhaps update the issue title and description and add everything required for the feature-request? I will happily hack with that. Seems pretty straight-forward to implement that (at least a basic version - not sure how to deal with dynamic runtime styles yet)

**Comment by troch** [comment]
So it's something which would solely benefit server-side rendering?

**Comment by rofrischmann** [comment]
@troch Yeah basically. Could help in the context of code-splitting.

@TxHawks One thing I figured: You're inserting the `<style>` tag directly before the DOM element. What if another DOM element in another sub-tree would need to use those styles? Aren't they scoped to that wrapping div?

**Comment by TxHawks** [comment]
@rofrischmann 
I'm not sure I understand the question, probably because I'm not aware of the internals of how this works, technically.
Ideally, I think that's how it should be, same as with adding new classes to the `<style>` tags in head today. If a class for the relevant rule had already been created, it is available and there for needn't be created again.

So, with the example above, if we had:
```js
const App = () => (
  <div>
    <Components />
    <Text />
    <Components />
  </div>
);

render(
  <Provider renderer={renderer}>
    <App />
  </Provider>,
  document.getElementById('app')
);
```

The HTML would be:
```html
<div id="app">
  <style  type="text/css">
    .a {color:#333}
    .b {font-size:36px}
  </style>
  <h1 class="a b">Example Title</h1>
  <style  type="text/css">
    .c {font-size:16px}
  </style>
  <p class="a c">Example paragraph</p>

  <!-- Second instance of Text -->
  <p class="a c">Example paragraph</p>

  <!-- Second instance of Components -->
  <h1 class="a b">Example Title</h1>
  <p class="a c">Example paragraph</p>
</div>
```

**Comment by Pranab16** [comment]
Any update when this will be available?

**Comment by robinweser** [comment]
Closing in favor of #754
