### ISSUE TITLE
Provide Fela Bindings for Hyperapp

### ISSUE THREAD

**Issue by osdevisnot** [robinweser/fela#539]
**Type**: Feature
-------------------
#### Proposal
Provide [Fela](http://fela.js.org/) Bindings for [Hyperapp](https://github.com/hyperapp/hyperapp), which would make Fela integrations with Hyperapp seamless.

#### Why ?
Created by @jorgebucaran. Hyperapp seems to be trending well in JS Framework land, and we want to try it out in our project where we use Fela for styling

![image](https://user-images.githubusercontent.com/802242/37571887-090f761a-2ac0-11e8-9e0c-da12337d6d5d.png)

NB: Creating a placeholder for now. Will fill in the details soon.

**Comment by rofrischmann** [comment]
Hey @osdevisnot,
Would you be open to send a PR with bindings? I'd love to the that being merged and released ;)

**Comment by jorgebucaran** [comment]
@rofrischmann Could you show us an example of fela bindings, maybe from a previous PR? 🙏

**Comment by rofrischmann** [comment]
Any help on this one? I'd love to have those bindings and might even try to implement them, but I don't have the time to experiment that much.

**Comment by robinweser** [comment]
As this PR has been stale for over 2 years, I'm now going to close it. If anyone still wants to help write Hyperapp bindings, feel free to do so! I'm more than happy to help with the process.
