### ISSUE TITLE
Feature Request: fela-plugin-validator to alert on props used that are not passed to Fela createComponent()

### ISSUE THREAD

**Issue by brianespinosa** [robinweser/fela#542]
#### Proposal
One very common issue my team and I experience when working in an application that is slowly moving to Fela components is when trying to use a prop inside of a component that is being passed down, we sometimes also miss explicitly defining passthrough props in `createComponent()`.

It would be great if fela-plugin-validator could alert us if we are trying to use a prop in a component (besides `className`) that has not been defined in `createComponent()`.

Obviously this is not an issue when using `createComponentWithProxy()` but unfortunately, anyone trying to use `createComponentWithProxy()` cannot use it in IE11 or less due to the inability to polyfill Proxy.

**Comment by sgrishchenko** [comment]
I think it is no possible realize without Proxy. How I can define that you trying read property inside Component? And fela-plugin-validator can not do this too. It does not know anything about components. It know only about rules, that you pass into `renderRule` renderer method (this is what actually does `createComponent()`). If you have good ideas - suggest (or pull request).

**Comment by brianespinosa** [comment]
I think I am proposing this as a solution in development environment. So if the solution to this requires the use of Proxy, then great. In a way, this seems like a lint type rule within a given file... which is why I was not sure if this plugin was the best place to suggest this.

**Comment by robinweser** [comment]
I'm closing this since it's been stale for over 2 years and `useFela` is the new recommended way to use Fela with React.
