### ISSUE TITLE
Feature request: Ability to undo `renderStatic`

### ISSUE THREAD

**Issue by alanhogan** [robinweser/fela#547]
**Type**: Feature

| Packages | Version |
| -------- | ------- |
| fela     | 6.1.3   |

-------------------
#### Description
There does not appear to be a way to remove styles added with `renderStatic`. Sometimes global styles are desirable only during particular application state. (E.g., a drag&drop library that requires a `move` cursor set on all elements during drag & drop.)

#### Proposal

Maybe `renderStatic` could return an object that could be passed to `unrenderStatic` or similar, similar to `subscribe`/`unsubscribe`.

**Comment by rofrischmann** [comment]
Sounds like the perfect use case for another enhancer! But feels like it could get quite tricky. How about undoing static styles rendered on the server? You would not have the returned object to undo that at all.

**Comment by robinweser** [comment]
Closing this in favor of #816
