### ISSUE TITLE
react-fela: A word on transitions / animations

### ISSUE THREAD

**Issue by kwirke** [robinweser/fela#580]
**Type**: Docs

| Packages | Version |
| -------- | ------- |
| fela     | 6.0.x   |

-------------------
#### Description
In trying to perform a simple CSS mount/unmount transition in react-fela, I had a hard time:

Trying to use `react-css-transition-group` was of no use, because it injects classNames into your component. That is kind of a colliding paradigm with Fela's state-in styles-out paradigm, because of how Fela generates the CSS classes dynamically.

I found out one animation / transition library which totally fits Fela's paradigm, [react-spring](https://github.com/drcmda/react-spring). React Spring generates and injects style props in your component so that the animation is drawn. A simple example of how they can live together (available as a gist in https://codesandbox.io/s/xr35825rv4) would be:

```javascript
const StyledTitle = createComponent(
  ({ opacity }) => ({
    opacity,
    color: "cadetblue"
  }),
  props => <h2 {...props}>I am transitioning!</h2>
);

const Item = ({ open }) => (
  <Transition
    from={{ opacity: 0 }}
    enter={{ opacity: 1 }}
    leave={{ opacity: 0 }}
  >
    {open ? props => <StyledTitle {...props} /> : () => null}
  </Transition>
);
```

I think it would be really nice to have such a comment on how to approach animations / transition in the react-fela docs.

**Comment by AugustinLF** [comment]
By the way, `react-transition-group` works really well with `react-fela`, since you'll pass a `entering | entered | exiting | exited` prop to your component, which let you work with animations directly with `createComponent`.

**Comment by kwirke** [comment]
Wow, I didn't know that. Do you have any example at hand? I imagine it's related to `@keyframes`, which I still need to dive deeper into.

My problem was less with animations than with CSS transitions on mount/unmount, which depends on React and the component's lifecycles.

Anyway, I think the docs could really receive a boost on that regard, and I'd be happy to help.

**Comment by AugustinLF** [comment]
Small example, not sure it "works", since it's a rough copy/paste from my codebase:
```javascript
import {Transition} from 'react-transition-group';

const NoteContainer = createComponent(({state}) => ({
    transition: '0.15s ease-in-out',
    overflow: 'hidden',
    extend: [
        {
            condition: state === 'entering',
            style: {height: 0},
        },
        {
            condition: state === 'entered',
            style: {height: '330px'},
        },
        {
            condition: state === 'exiting',
            style: {height: '330px'},
        },
        {
            condition: state === 'exited',
            style: {height: 0},
        },
    ],
}));

const Comp = ({isOpen}) => (
    <Transition in={isOpen} timeout={150}>
        {(state) => <NoteContainer state={state} />)}
    </Transition>
);
```

And yep, I agree that docs could be improved, I'm pretty sure your example could end up in the docs, feel free to open a PR :)

**Comment by rofrischmann** [comment]
Any kind of PR that improves the usage experience with Fela is always welcome =)
I actually did not use any of those tools but plain old keyframes all the time, can't tell what works best.
Only thing I can tell you: If you're animating properties with dynamic values (in cases where keyframes might not work) you should consider using inline style instead of Fela as creating new CSS classes etc. might lead to an overhead here.

**Comment by kwirke** [comment]
Thank you both!
I can see my implementation can indeed affect performance, since it will re-render quite an amount of times, instead of letting the transition to the native CSS engine, as @AugustinLF 's solution does.

I adapted the gist to the solution he proposed using `react-transition-group`: https://codesandbox.io/s/0y3734p5vn

I was using version 1.x, that's why I didn't find this feature.

I will come back with a PR for the docs.

**Comment by brianespinosa** [comment]
Lovely stuff, @kwirke, @AugustinLF. Thanks for sharing. I really love this solution... significantly more than one I implemented in my own application. And I was not thinking about the performance issue that @rofrischmann mentioned. I am definitely going to rework how this is implemented in my own ecosystem now. Great idea adding this to the docs.

**Comment by jwineman** [comment]
Has this been PRd to the docs yet?  I'd be happy to do it while its fresh in my mind if not.

I modified the above solutions slightly:
```
// @flow

import * as React from 'react';
import { createComponentWithProxy } from 'react-fela';
import Transition from 'react-transition-group/Transition';

const getOpacity = transitionState => {
  switch (transitionState) {
    case 'entered':
      return 1;
    case 'entering':
      return 0;
    case 'exiting':
      return 0;
    case 'exited':
      return 0;
    default:
      return 0;
  }
};

type FadeProps = {
  className: string,
  children: React.Node,
  timeout: number,
  transitionState: 'entering' | 'entered' | 'exiting' | 'exited'
};

const FADE_THEME = ({ transitionState, timeout }: FadeProps) => ({
  transition: `opacity ${timeout}ms ease-in-out`,
  opacity: getOpacity(transitionState)
});

const FadeContainer = ({ children, className }: FadeProps) => (
  <div className={className}>{children}</div>
);

const FelaFade = createComponentWithProxy(FADE_THEME, FadeContainer);

type Props = {
  key?: string,
  children: React.Node,
  timeout: number
};

export const FadeTransition = ({ children, timeout, ...props }: Props) => (
  <Transition timeout={timeout} {...props}>
    {transitionState => (
      <FelaFade transitionState={transitionState} timeout={timeout}>
        {children}
      </FelaFade>
    )}
  </Transition>
);

export default FadeTransition;
```
Use case:
```
<FadeTransition in timeout={500} appear>
            faded text
</FadeTransition>
```

**Comment by rofrischmann** [comment]
Would love to see a PR! Never actually happened

**Comment by robinweser** [comment]
Closing since it's been stale for a long time.
