### ISSUE TITLE
Problems with fela-enzyme

### ISSUE THREAD

**Issue by UberMouse** [robinweser/fela#618]
**Type**: Bug

| Packages | Version |
| -------- | ------- |
| fela     | 5.0.4   |
| react-fela | 5.1.1 |
| fela-enzyme | 1.0.2 |

-------------------
#### Description
| Packages | Version |
| -------- | ------- |
| enzyme | 3.3.0 |
| enzyme-adapter-react-16 | 1.1.1 |

I'm having a few problems with fela-enzyme

1. felaShallow doesn't seem to work at all, if I attempt to use it I get an error about the `<Provider/>` being missing
2. felaMount (after I manually patched the exports to get it exported, see #617) does not seem to be passing the theme through correctly. My component is getting passed an empty object for a theme. If I log out the theme passed to felaMount in felaMount.js it is the correct theme object however.

Is this potentially because I'm still on fela 5.x.x. Has something changed in how the context is passed down for 6.x.x that fela-enzyme has been designed for?

#### Steps to reproduce
1. Create fela component
2. Shallow render fela component with felaShallow
3. Error about missing `<Provider/>`

.
1. Create fela component that using a nested Theme property
2. Mount fela component with felaMount
3. Component raises an error about being unable to access property of undefined

**Comment by rofrischmann** [comment]
@HamidAghdaee can you check that?

**Comment by TxHawks** [comment]
Seems like fela-enzyme is still importing `createTheme`  from `fela-binding`, but `createTheme` was using the old context api, and was deprecated in 491567f697416c4bb051c13bc689d12aaa028409

@sgrishchenko Would you mind fixing it?

**Comment by robinweser** [comment]
We're going to deprecate fela-enzyme as it's not maintained and the original author did not respond at all. I'd recommend using jest-react-fela for simple testing.
