### ISSUE TITLE
Moving to scoped packages in NPM

### ISSUE THREAD

**Issue by TxHawks** [robinweser/fela#699]
**Type**: Discussion

#### Description
Manually managing permission for the publishing of individual packages on npm is annoying and error prone, as illustrated by [#698 (comment)](https://github.com/rofrischmann/fela/issues/698#issuecomment-481367292_). Basically the person who first publishes the package has to remember to manually add permission for the other maintainers.

#### Proposal
Scoped packages solve this issue, as different people can be associated with the organization, and permissions are handled in one single place. 

the `@fela` scope is taken, but is apparently empty. I've contacted npm about this, and they responded that they will contact the current owners of `@fela` about passing it over to us.

They should get back to me within  few weeks, depending how responsive the person/people that are currently in possession of the scope are.

I think we should wait a reasonable time for their reply, but also consider  alternatives such as `@felajs`, `@fela.js` or `@fela-js` in the meanwhile.

**Comment by rofrischmann** [comment]
@TxHawks Any news on transferring @fela?

**Comment by TxHawks** [comment]
Yes! npm got back to me yesterday that they have contacted the owners of `@fela` and have given them until the 9th to respond. It seems inactive, and if there is no response, they will start the process of transferring it over to us.

**Comment by TxHawks** [comment]
Okay, `@fela` was just transferred to us, so we can start migrating.

I think we should probably remove the `fela-` prefix from all packages, so that e.g., `fela-bindings` becomes `@fela/bindings`. Only question is what should we do with `fela`. I think we should probably follow suit with Babel, and go for `@fela/core`.

**Comment by TxHawks** [comment]
Now that GitHub has announced its own package registry, should we plan to also publish here? I've already checked and the `@fela` scope is taken (well, not as a scope, but there's a user with that handle). It seems like a pretty low-activity account, so he may be willing to pass it over to us.

@rofrischmann What do you think?
