### ISSUE TITLE
Why is enzyme-to-json a peer dependency in fela-enzyme?

### ISSUE THREAD

**Issue by rapheld** [robinweser/fela#719]
**Type**: Question

| Packages | Version |
| -------- | ------- |
| fela-enzyme     | 10.5.0   |

-------------------
#### Description
I just added fela-enzyme. When I tried using it got an message that enzyme-to-json wasn't available. The package.json has it listed as a peer dependency, so I'll have to install/manage that separately. Any specific reason it is set up that way? Wouldn't it be better to have enzyme-to-json as a regular dependency?

BTW, fela on Gitter appears dead

**Comment by weserio** [comment]
First of all, we should make it a dependency - thanks for reporting! (wanna send a PR?)
I do not personally use fela-enzyme and thus never really used/checked it - it was PRed as well.

Any improvements to the package are very welcome!

Also, we moved to Spectrum recently (see README). Where did you find the reference to Gitter?

**Comment by rapheld** [comment]
Thanks for the response. I'll try to find some time for a PR. Also, Gitter is mentioned in the Github Issues template:
> Before choosing question, please consider asking on Gitter as we might close question issues

**Comment by weserio** [comment]
Ohh, we'll need to update all occurrences of Gitter mentions! Also according to the package. I'm not even sure if you really need it at all. We only use snapshot tests (with jest-react-fela) and it works just fine enough. I'm happy with any contribution of course, just wanting to hint that!

**Comment by robinweser** [comment]
We're going to deprecate fela-enzyme as it's not maintained and the original author did not respond at all. I'd recommend using jest-react-fela for simple testing.
