### ISSUE TITLE
Enzyme mount recipes not updated for latest fela

### ISSUE THREAD

**Issue by danielantelo** [robinweser/fela#720]
https://github.com/weserio/fela/blob/master/docs/recipes/TestingFelaComponents.md

in the `#test-helpers/felaMount.js` example it says `import { createTheme } from 'fela-bindings'` which is no longer in the fela-bindings package.

Could we get an updated recipe? thanks.

**Comment by horaklukas** [comment]
From the same reason, `fela-enzyme` doesn't work anymore. `felaShallow` fails with ` TypeError: (0 , _felaBindings.createTheme) is not a function` error 🙁

**Comment by robinweser** [comment]
See the latest comment in Spectrum:
```
Hey guys,
sorry for the late response - I've been out for my honeymoon for 3 weeks :)
fela-enzyme was merged in as a third-party library, but the author did not respond to any issues since then so it kinda wasn't maintained for a while.
Feel free to update the lib (Im happy to help!)
Otherwise I'd just recommend using jest-react-fela and do snapshot testing
Sorry for the inconvenience
```

**Comment by robinweser** [comment]
We're going to deprecate fela-enzyme as it's not maintained and the original author did not respond at all. I'd recommend using jest-react-fela for simple testing.
