### ISSUE TITLE
No typings in `fela-plugin-typescript`? Has somebody tried?

### ISSUE THREAD

**Issue by efoken** [robinweser/fela#731]
**Type**: Question / Bug

| Packages | Version |
| -------- | ------- |
| fela     | 10.6.1   |

-------------------
#### Description
Has somebody of you tested the `fela-plugin-typescript`? For me there are no typing available in the package, if I install it using npm or yarn, like `npm i --save fela-plugin-typescript`

#### Steps to reproduce

1. Install `fela` and `fela-plugin-typescript` using npm
2. Try to initialize the TypeScript plugin
3. See, that there is an error, where no typing are available
4. Look inside your `node_modules/fela-plugin-typescript` that there is no file like `index.d.ts`, like it is in the GitHub repository

#### Expected Behavior
```javascript
import { createRenderer } from 'fela';
import typescript from 'fela-plugin-typescript';

createRenderer({
  plugins: [typescript()],
})
```

#### Actual Behavior
```
Could not find a declaration file for module 'fela-plugin-typescript'.
```

**Comment by robinweser** [comment]
Seems solved with #729?
