### ISSUE TITLE
Bug: fela-bindings 10.6.0 & 10.6.1 breaks react-native

### ISSUE THREAD

**Issue by MrOggy85** [robinweser/fela#736]
| Packages | Version |
| -------- | ------- |
| fela-bindings     | 10.6.0 & 10.6.1   |

-------------------
#### Description
In react-native environment `window` is defined, but `document` is undefined. The function `hasDOM` will use `document` which results in the error:
`document is not defined`.

I think an additional check needs to be made to assure that `document` is not used when `window` is present. Before the refactoring in 10.6.0 there were additional checks with the `renderer` object before using `document`. I think some of that code needs to be reverted.

This is a serious bug as it retroactively breaks all versions of `react-fela` that is using the semver version ^10.x.x of `fela-bindings`. 

The current workaround we are using is to use a [`resolutions`](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) section in our package.json to fix the `fela-bindings` version to 10.5.0. This of course prevents us from updating to 10.6.1 of `fela`. 

```
"resolutions": {
    "react-fela/fela-bindings": "10.5.0"
  }
```

I made a comment on this issues https://github.com/robinweser/fela/issues/727 https://github.com/robinweser/fela/pull/728, but since it's closed I made this issue. That fix is ok, but the problem with react-native is still present since it came with version 10.6.0 of `fela-bindings`

#### Steps to reproduce
1. Start the app

#### Expected Behavior
```javascript
// no error
```

#### Actual Behavior
```javascript
`document is not defined`
```

**Comment by robinweser** [comment]
Hey there,

Thanks for opening that issue!
Would you be willing to file a PR adding those checks? Must have gone missing by accident.
