### ISSUE TITLE
Generating supports rules doesn't work in devMode

### ISSUE THREAD

**Issue by horaklukas** [robinweser/fela#741]
**Type**: Bug

| Packages | Version |
| -------- | ------- |
| fela     | 10.5   |

-------------------
#### Description
Rendering `@supports` rule doesn't work when `devMode: true` set.

#### Steps to reproduce

1. Create renderer with `devMode: true`
2. Use `@supports` rule for any element, eg.
    ```
     '@supports (display: grid)': {
        display: grid,
     }
    ```

#### Expected Behavior
`display: grid` should be applied in newer browsers

#### Actual Behavior
Rule is not applied

I figured out that the problem is at `fela-dom/src/dom/connection/insertRuleInDevMode.js` where is the expression `sheet.support === support` which evaluates to `"true" === true` for support-type sheet list. 

I Experimentally fixed it by changing `support: true` to `support: "true"` at `fela-dom/es/server/renderToSheetList.js`, but I'm not sure if it's a correct solution.

**Comment by robinweser** [comment]
Fixed that in master, releasing soon.
