### ISSUE TITLE
Descendant Selectors / combinators

### ISSUE THREAD

**Issue by lostpebble** [robinweser/fela#746]
**Type**: Feature / Question

Hi @robinweser and contributors,

This is a similar issue to #169 - but it feels like you resolved that one. So thought I'd open a new one to give a fresh look at this.

I need to make use of a [descendant combinator](https://developer.mozilla.org/en-US/docs/Web/CSS/Descendant_combinator) similar to what was being asked on that first issue.

For my example, I have a Text component, which adds a bunch of styles through a Fela rule:

```ts
return {
    fontFamily: "serif",
    fontSize: size,
    color: colorProp,
    display: block ? "block" : "inline-block",
    textTransform: transform,
    fontWeight: weight as FontFaceFontWeightProperty,
    letterSpacing: spacing,
    textAlign: align,
    lineHeight,
    margin,
    whiteSpace,
  };
```

It might be used like so (in React):

```tsx
<FelaText>Hello</FelaText>
```

But now I'm realizing that I'd really like to be able to put text within this component, but allow sections of that text to be styled differently according to `<b>`, `<i>`, `<code>` etc.

So I've added these rules:

```ts
return {
    "> b": {
       fontWeight: "bold",
    },
    "> i": {
      fontStyle: "italic",
    },
    "> code": {
      fontFamily: "monospaced",
    },
    fontFamily: "serif",
    fontSize: size,
    // ... the rest
```

This is all fine, unless I decide to use more than one of those in my inner text styling:

```tsx
<FelaText><i>Hello <b>World</b></i></FelaText>
```

Since now `<b>` is not longer a **direct** descendant of the rule - and hence `> b` doesn't apply anymore.

I've ended up with a rule looking like this now:

```ts
return {
    "> b": {
      fontWeight: "bold",
      "> i": {
        fontStyle: "italic",
      },
    },
    "> i": {
      "> b": {
        fontWeight: "bold",
      },
      fontStyle: "italic",
    },
    // ... the rest
  };
```

But obviously that is not scalable, as I might want to put bold within `<code>` as well, and the tags might appear in different orders- so its basically an explosion of combinations.

Is there any way in which I can get Fela to create a descendant CSS selection which isn't only direct?

I see `>>` was mentioned in the previous issue - but I tried that and it doesn't seem to do anything.

**Comment by robinweser** [comment]
You can always use e.g. `'& b'` to add ANY valid CSS selector, but it's considered an escape hatch rather than a built-in feature. Hope that solves your issue here, in general I more like to remove selectors than adding new ones 😅

Reopen if that doesn't work/solve your issues :)

**Comment by lostpebble** [comment]
Worked perfectly! Thanks.

Don't know why I didn't try that... I just assumed the `&` operator made a combination of two selectors / classes at the same level. But I see now it is often used for descendant too.

And yea, I totally get your philosophy with Fela and using less child selectors. Its just that for text especially, its nice to be able to easily create descendant selectors because of all the minor tweaks that always pop up in styling.
