### ISSUE TITLE
Request: Document what prefixes are added with Prefixer and/or allow more control

### ISSUE THREAD

**Issue by alanhogan** [robinweser/fela#755]
**Type**:  Docs 

| Packages | Version |
| -------- | ------- |
| fela     | 11.0.x   |

-------------------
#### Description
We have an upcoming project to trim a little fat by removing polyfills for Internet Explorer and other ancient browsers. I am having a hard time understanding if there is anything I can or should do to make the prefixer do "less prefixing", or what versions of Chrome (for example) might be affected if we removed the prefixer altogether.

**Comment by robinweser** [comment]
Hmm, this is not really a Fela thing here.
You should find all the information at [inline-style-prefixer](https://github.com/robinweser/inline-style-prefixer).

It supports custom builds with minimum browser versions. You might have to reimplement fela-plugin-prefixer, but it‘s literally just a one liner (just check the source).

Hope this helps, if not feel free to reopen the issue!
