### ISSUE TITLE
ThemeContext is exported from react-fela but type definitions do not show it

### ISSUE THREAD

**Issue by sushruth** [robinweser/fela#757]
**Type**: Bug / Feature / Infrastructure / Docs / Question

| Packages | Version |
| -------- | ------- |
| fela     | 6.0.x   |

-------------------
#### Description

`ThemeContext` is exported from react-fela but type definitions do not show it. ThemeContext must be declared as a valid export from `react-fela`.

#### Steps to reproduce

NA

#### Expected Behavior
NA

#### Actual Behavior
NA

**Comment by robinweser** [comment]
Feel free to send a PR adding types!
I'm not using TypeScript hence not interested in doing it myself :P
