### ISSUE TITLE
FelaComponent missing style object for React Native

### ISSUE THREAD

**Issue by jstorm31** [robinweser/fela#762]
**Type**: Question / Bug

I've noticed `FelaComponent` provides `className` prop to its children even though it is explicitly mentioned [in the docs](http://fela.js.org/docs/guides/UsageWithReactNative.html) to apply styles using `style` and not `className`. Is this intentional? It might be removed from the docs or fixed in `FelaComponent` then.

| Packages | Version |
| -------- | ------- |
| fela-native     | 11.0.2   |
| react-fela     | 11.0.2   |

**Comment by robinweser** [comment]
Oh this is not intentional. It should pass `style` in React Native since `className` is web-only.
Would you mind sending a PR for that? Would really appreciate any help here!

**Comment by jstorm31** [comment]
Of course, I can do a PR! 🙂
