### ISSUE TITLE
Animations are not properly rehydrated

### ISSUE THREAD

**Issue by HugoGiraudel** [robinweser/fela#770]
Hello Robin! 👋

**Type**: Bug

| Packages | Version |
| -------- | ------- |
| fela     | 11.x   |

-------------------
#### Description

With SSR, when using 2 animations (one iso, one client-side only), the rehydration does not work properly and names end up being conflicting. That is, both animations will be named `k1`, resulting in a rendering issues.

**Comment by TxHawks** [comment]
fela-dom's [rehydrate.js#L14-L74](https://github.com/robinweser/fela/blob/0c2eeff849b52c956ae8203e22c0fe26c4c0f2b6/packages/fela-dom/src/dom/rehydrate.js#L14-L74) is probably at fault. It simply doesn't cover keyframe animations, static rules and font declarations.
