### ISSUE TITLE
Background-image property with inlined image removed without warning

### ISSUE THREAD

**Issue by horaklukas** [robinweser/fela#772]
**Type**: Bug

| Packages | Version |
| -------- | ------- |
| fela     | 10.8.2   |

-------------------
#### Description
I'm using base64 encoded image as background image, but every time I do it, it's removed from style without any warning or error in console.

My code looks like
```js
import myBgImage from '!url-loader!../images/my-image.png';

const placeholder = ({ theme }) => ({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',

    width: '100%',
    height: '100%',

    backgroundImage: `url(${myBgImage})`,
    color: theme.colors.white,
});
```

I was curious why it is happening so 've deep dived into the fela packages and find out where is the problem. 
It's the [`isUndefinedValue`](https://github.com/robinweser/fela/blob/master/packages/fela-utils/src/isUndefinedValue.js#L6) function in `fela-utils`, because there is a "null" inside my encoded image. This is a fragment of the `axsir3fs3y5csnull9u6wQuc03Z1Wp`.

**Comment by robinweser** [comment]
Woah, that's a coincidence here!
Lemme see how to work around that issue without removing the safety of null values.

**Comment by horaklukas** [comment]
Wow that was quick, thanks a lot for your great job 👏
