### ISSUE TITLE
Some browser specific css rules (-webkit*, -ms*, -moz*) not rendered

### ISSUE THREAD

**Issue by jancama2** [robinweser/fela#783]
**Type**: Bug 
| Packages | Version |
| -------- | ------- |
| fela     | 11.2.0   |
| react-fela     | 11.2.0   |
| fela-monolithic     | 11.2.0   |
| fela-plugin-expand-shorthand    | 11.2.0   |
| fela-plugin-fallback-value     | 11.2.0   |
| fela-plugin-friendly-pseudo-class     | 11.2.0   |
| fela-plugin-named-keys     | 11.2.0   |
| fela-plugin-unit     | 11.2.0   |

-------------------
#### Description
I'm adding code to hide scrollbars by css rules. Rules 
```
MsOverflowStyle: '-ms-autohiding-scrollbar',
WebkitOverflowScrolling: 'touch',
```

won't get rendered and no error is thrown in the console.

It is interesing that for example rules like 
```
WebkitAppearance: 'none',
WebkitTapHighlightColor: 'transparent',
```
get rendered without any problems.

#### Steps to reproduce

Try to use any of previously mentioned rules.

#### Expected Behavior
Render rules like
```
-ms-overflow-style: -ms-autohiding-scrollbar;
-webkit-overflow-scrolling: touch;
```

#### Actual Behavior
The rules wont get rendered.

**Comment by robinweser** [comment]
On which browser are you testing? Safari for example simply removes rules that are not supported (e.g. `-webkit-overflow-scrolling`) so this is not an issue with fela (since we don't care what property-value pair you pass, but it's actually you're browser throwing if an invalid rule render is attempted)

**Comment by jancama2** [comment]
I see, now it makes sense. Is this behaviour documented somewhere? Because I expected to see the rule rendered anyways and disabled by a browser. Maybe would be better to at least log an error into the console in the dev mode.

But thanks for help!

**Comment by jancama2** [comment]
Btw what is the validator plugin for then? I would expect it logging an error about not supported rule, but didn't log anything. My setup is :
```
felaPluginValidator({
            logInvalid: true,
            deleteInvalid: false,
            useCSSLint: false,
        })
```

**Comment by robinweser** [comment]
So the rule is rendered in `devMode`, but won't in production. That's because we use `insertRule` in production and that's simply the way how `insertRule` works.
It'd probably show tons of warnings if we enabled that (e.g. Safari would log any other prefix than -webkit-). Tbh, I have never used the validator plugin myself, it was rather a community-driven plugin, but it's made to find your style issues e.g. typos, wrong value types or whatever and is not concerned about browser support of props (it won't throw on `-webkit-overflow-scrolling` since that's a valid prop for some browsers).

**Comment by jancama2** [comment]
Hmm, right, devMode was the problem, I had it set to false 🤦. But thanks anyways, I've learned something new :D

**Comment by robinweser** [comment]
You're welcome :) Might still be good to add that somewhere in the docs. One usually does not call `insertRule` manually from a product perspective, so most ppl won't know that!

**Comment by jansindl3r** [comment]
Hello, I feel like this might be similar, but why am not I not able to use `input[type=range]::-webkit-slider-thumb` selector?

**Comment by robinweser** [comment]
Can you give me a full code example of what you‘re trying to do here?

**Comment by jansindl3r** [comment]
Am trying to customize range input as here for example - [css-tricks](https://css-tricks.com/styling-cross-browser-compatible-range-inputs-css/) 

```javascript
const inputRule = () => ({
  "&::-webkit-slider-thumb": {
    appearance: "none",
    "-webkit-appearance": "none",
    width: "40px",
    height: "40px"
  }
})
```

```jsx
<input className={css(inputRule)} type="range" />
```

some classes are assigned to the element, but they are empty. They are not listed in development tools in chrome under "styles"

```html
<input class="au av aw ax" type="range"/>
```

what am I doing wrong? Thanks for this useful tool!

**Comment by robinweser** [comment]
I seems like these rules are "illegal" in the browser then. Not sure what the issue is.
Here's what I am using in a custom project and it works just fine.

```js
const style = {
  '::-webkit-slider-thumb, ::-moz-range-thumb, ::-ms-thumb': {
    ...
  }
}
```

> Note: I am using [fela-plugin-multiple-selectors](https://github.com/robinweser/fela/tree/master/packages/fela-plugin-multiple-selectors) to resolve the comma-separated list of selectors.
