### ISSUE TITLE
React example doesn't appear to work

### ISSUE THREAD

**Issue by jjenzz** [robinweser/fela#785]
I was hoping to give Fela (`v11.2.0`) a try so spun up the example from the README in a sandbox, but it doesn't work: https://codesandbox.io/s/fela-demo-udwmh

It seems to be something to do with the provider. I have tried both `FelaProvider` and just `Provider` without luck. 

Any idea what I am doing wrong here? It would be really helpful to have a complete working sandbox example from the repo 🙏🏻

**Comment by robinweser** [comment]
Funny that no one ever found this before, the example was wrong it's `RendererProvider` not `FelaProvider`. See https://codesandbox.io/s/fela-demo-7tsj5

I updated the README accordingly.
Thanks for bringing this up and trying out Fela :)
