### ISSUE TITLE
Missing rehydrate and targetDocument prop in TypeScript.

### ISSUE THREAD

**Issue by HeroBanana** [robinweser/fela#787]
Dear Robin,

I guess the typing is missing some props.

https://github.com/robinweser/fela/blob/97148419e7941dbd5867b35df6ac4de6c5ed3e55/packages/react-fela/index.d.ts#L34

https://github.com/robinweser/fela/blob/97148419e7941dbd5867b35df6ac4de6c5ed3e55/packages/react-fela/src/RendererProvider.js#L14

I would love to see support for the following:
```typescript 
  interface ProviderProps {
    renderer: object;
    rehydrate?: boolean;
    targetDocument?: any;
  }
```

**Comment by robinweser** [comment]
Feel free to send a PR adding those :)
