### ISSUE TITLE
How can I renderRule between multiple ReactDom.render

### ISSUE THREAD

**Issue by zerofront** [robinweser/fela#788]
**Type**: Bug / Question

| Packages | Version |
| -------- | ------- |
| fela     | 11.2.x   |

-------------------
#### Description
I use RendererProvider、ThemeProvider 、themeContext、renderRule to build my components, It works well. 

but when I want to render a component by calling `notice.open('some notice')`. 
so I use `ReactDom.render(<Notice />, document.body)`

and I found renderRule return nothing.

**Comment by jancama2** [comment]
Not fela related issue, but an interesting one though. You are rendering a notice in a new react tree so there is no access to the `RendererProvider` and its renderer I guess. Use react portals to be able to render to a different node but stay in the same react tree or wrap the `<Notice />` with the provider.

**Comment by robinweser** [comment]
I think @jancama2 correctly described the issue here. Will close this one, but feel free to reopen if you think it's still an issue.
