### ISSUE TITLE
Emotion-style css prop support

### ISSUE THREAD

**Issue by stephenh** [robinweser/fela#791]
I'm currently using Emotion and really liking the API of their `css` prop, i.e.:

```
<div css={{ marginTop: "1px" }}>...</div>
```

Which, for non-changing styles, just seems more direct (and more inline-markup-friendly) than fela-react's current "define a `const rule` + `useFela` hook + `css(rule)`" approach, although I get the current approach also makes more sense when you have complicated/large rule logic that you don't want inline anyway.

Would it be possible/likely for fela-react to support both styles, i.e. current `const rule`+`useFela` as well as a `css=` prop?

Fwiw perhaps there is something fundamentally different about the `css=...` approach that makes optimization harder/unlikely/etc (i.e. it seems like the module-level `const rule =` might help caching/perf b/c it has a persistent identity/reference across renders). This seems likely, but I'm not sure, and naively Emotion "seems to be doing fine?" (I don't have any perf numbers either way), so just thought I'd ask.

Thanks!

**Comment by robinweser** [comment]
Hey there!

So this is already possible, check out the `fe` jsx pragma: http://fela.js.org/docs/api/bindings/fe.html.
You're also able to replace it at an app level using webpack.

Also looking at the hook approach, you don't necessarily have to use a rule function, but can pass pure objects in all React bindings e.g. 
```js
const Heading = ({ children }) => {
  const { css } = useFela()

  return <h1 className={css({ fontSize: 26, lineHeight: 1.5, color: "blue" })}>{children}</h1>
}
```

Hope that helps!
Going to close this issue, feel free to reopen if it doesn't.

**Comment by stephenh** [comment]
Oh no! I swear I looked in the docs. :grimacing: :-) Thank you!

**Comment by stephenh** [comment]
@robinweser it looks like the `import { fe } from react-fela` doesn't work in TypeScript b/c the `fe` is not in the `.d.ts` typings; I assume this is probably not surprising? Is it okay to file a new issue about that? I might poke around at fixing, although it depends on how deep the rabbit trail goes.

**Comment by robinweser** [comment]
I'd appreciate a PR to fix it since I'm not using TS myself and thus am not likely to fix that any time soon.
