### ISSUE TITLE
Support selectors with two ampersands 

### ISSUE THREAD

**Issue by stephenh** [robinweser/fela#793]
While it's a bit odd, `.foo + .foo` is technically a valid selector.

In fela, if I use the `&` syntax to do this, i.e. `"& + &": { ... }`, the generated selectors is `.c + &`, i.e. only the 1st `&` got replaced with the class name and not the 2nd.

**Comment by robinweser** [comment]
Heyhey,
Yep true, we only replace the first one as we want to keep the logic as simple as possible.
It's rather discouraged to use selectors at all in Fela as that's against its core principles.
You might be interested in https://github.com/robinweser/fela/tree/master/packages/fela-identifier which can help to solve that issue. It might look more complex at first (and pbly is), but that's the recommended way to break out of the concepts atm.

**Comment by stephenh** [comment]
Ah cool, thanks for that link. That "on parent hover, style a child" is a use case we'd come across / struggled with as well :-). The identifier approach looks nice, I'll keep that in mind...

**Comment by robinweser** [comment]
Going to close this issue.
Have thought about it again and suddenly realized that the concept of ampersands doesn't make any sense in Fela since each property-value is rendered to a globally reused CSS class. Thus those ampersands cannot simply be replaced with a "specific" class name.

**Comment by stephenh** [comment]
> property-value is rendered to a globally reused CSS class

Oh sure, that makes sense. Thanks!
