### ISSUE TITLE
Fela UMD does not work in IE11

### ISSUE THREAD

**Issue by IgorBabkin** [robinweser/fela#799]
**Type**: Bug

| Packages | Version |
| -------- | ------- |
| fela     | 11.2.x   |

-------------------
#### Description
IE11 complains for arrow functions

#### Proposal
Compile sources to ES5

**Comment by robinweser** [comment]
Would you be open to send a PR changing the build scripts to ES5 output? I'm not that much into Webpack anymore and don't have the time to do that as I don't use the UMDs either.

**Comment by IgorBabkin** [comment]
Sure!

**Comment by robinweser** [comment]
Closing as we don't have arrow functions in the newer UMD builds anymore
