### ISSUE TITLE
Conditional styling on body, html and other "global" document things

### ISSUE THREAD

**Issue by lostpebble** [robinweser/fela#816]
**Type**: Feature

#### Description

There have been cases where, based on a selected theme or other app variable, I would like to change the css that is applied to the `html` or `body` tag. Or just all tags in general inside the document, with a root `* { }`.

Currently with Fela it doesn't seem this is possible. We only have `renderer.renderStatic()` to apply root document styles, but this is not conditional in any way- once the styles are printed, they're there to stay.

#### Proposal

Would be cool if there was an interface which allowed us to simply replace a subset of styles applied to these elements, like the regular render static `<style type="text/css"/>` block but completely replaceable. So, `renderer.renderStatic()` but each time it is called, all the static styles are just replaced with the new ones.

**Code Example**:
```javascript
// Somewhere in the code, maybe in response to a theme change

styleRenderer.renderStaticOverwrite(`
*::-webkit-scrollbar-track {
    -webkit-box-shadow: inset 0 0 3px 1px rgba(37, 47, 67, 0.3);
    border-radius: 0 10px 0 10px;
    width: 11px;
    height: 11px;
    overflow: hidden;
    background-color: #a8b0bb;
}`);
```

In this example, we might want to change the color of the scrollbar's track conditionally depending on the theme.

To help with modularization, perhaps such "overwritable" static style blocks could be (optionally?) namespaced. So maybe the API could be like so:

```ts
styleRenderer.renderStaticOverwrite(` // scrollbar static styling `, "scrollbar");
```

**Comment by robinweser** [comment]
I think this is somewhat related to https://github.com/robinweser/fela/issues/547.
We might want to create an enhancer that overwrites renderStatic that returns a `remove` function. Using that, we should be able to achieve to above-mentioned approach without having to deal with unique namespaces.

**Comment by lostpebble** [comment]
I think that could work as well. My reasoning for preferring a "namespace" in this is because its much easier to create and pass enums around than to keep track of subscriptions functions.

Just an important note, I don't actually want to "remove" these styles- I want to directly replace them. Removing them and then replacing them could have ramifications for rules like `transition`.

I suppose we could do something along the lines of:

```ts
const staticScrollbarStyles = renderer.createStaticStyleBlock();

staticScrollbarStyles.replace(` // css here `);
staticScrollbarStyles.remove();
```

This gives us the best of both worlds? And these "blocks" would each be isolated and "namespaced" automatically. Though, you only really need `.replace()` - since you can just pass an empty string to remove the styles.

These would have to be universally viable too- as I'd like to set these kinds of global styles depending on a user's account setting for their theme before server-rendering the page, and of course be able to allow them to change those styles on the SPA afterwards too.

> We might want to create an enhancer that overwrites renderStatic that returns a remove function.

Would it be possible to create an enhancer that overwrites `renderStatic` to return a `replace` function? (which will function with SSR) I think that would cover all requirements.

But it does seem tricky to achieve for SSR without some sort of namespace to identify which style block we are referring to, which was previously generated server-side, so maybe the ending API might be forced to look something like this:

```ts
const staticScrollbarStyles = renderer.createStaticStyleBlock("namespace_here");

staticScrollbarStyles.replace(` // css here `);
staticScrollbarStyles.remove();
```

**Comment by chrisrzhou** [comment]
Hitting the same use case here!  I think there maybe a few ways that developers could use this in the form of:
- a cleanup function returned by `renderStatic`
- an update to `renderStatic` so that it will always overwrite static styles (BREAKING CHANGE)
- a new API method called `resetStatic` that explicitly resets static styles (developers would be free to use the existing `renderStatic` and `resetStatic` based on their needs).

I think I prefer the third approach although I'm not sure if it makes sense or the right approach for the `renderer`'s API!

**Comment by lostpebble** [comment]
Agreed that this still needs to be solved, but I'd like to point out an important point I mentioned earlier:

> Just an important note, I don't actually want to "remove" these styles- I want to directly replace them. Removing them and then replacing them could have ramifications for rules like `transition`.

If there is any "cleaning" / "reset" step between inserting the new styles, we'd lose things like the background of the site fading from black to white (dark mode to light mode) etc. So it needs to have the ability to do a direct "replace" the CSS rules. I don't think any of your suggestions included that ability.
