### ISSUE TITLE
Website Improvements

### ISSUE THREAD

**Issue by robinweser** [robinweser/fela#829]
With #818 being merged, we have a completely new website for Fela!

Now it's time to gradually improve it. 
Here's a short list of things that would be nice-to-have:

- [ ] Intro
  - [ ] Performance
- [ ] Recipes
  - [ ] Extending Components
  - [ ] Testing Components -> add fela-monolithic
- [ ] Resources Page
- [ ] Redesign Landing Page

**Comment by eniolajayi** [comment]
Hello @robinweser 👋.  I'm a front-end dev and student and I would love to help out with this issue! Where do I start?
