### ISSUE TITLE
Could you upgrade csstype version ?

### ISSUE THREAD

**Issue by Him-2C** [robinweser/fela#835]
**Bug / Feature**

 Csstype in Fela and Fela-Plugin-Typescript are using csstype version 2, so this version not good typescript autocomplete
For example display, flex and etc.

Could you upgrade csstype version? Is perfect if you can.

| Packages | Version |
| -------- | ------- |
| fela     | 11.5.0   |

- csstype 2
![image](https://user-images.githubusercontent.com/30730045/102341169-05e88400-3fca-11eb-97ba-5003c033ed5a.png)

- css type 3

![image](https://user-images.githubusercontent.com/30730045/102341425-67a8ee00-3fca-11eb-9962-2eac29db6feb.png)

**Comment by robinweser** [comment]
Feel free to do that yourself :)
Should be as easy as updating the version and submitting a pull request, can even be done on GitHub directly.

I don‘t use TypeScript and thus have no priority for that

**Comment by robinweser** [comment]
The line that needs to be changed can be found here: https://github.com/robinweser/fela/blob/master/packages/fela/package.json#L40

**Comment by Him-2C** [comment]
@robinweser  Thank you very much.

**Comment by veeramarni** [comment]
@robinweser could you please merge this PR?

**Comment by robinweser** [comment]
Can someone confirm that those major changes in version 3 are not breaking anything in our implementation? As I don't use TypeScript I can't do that due to lack of knowledge. Seemed to me that we might have issues with those changes right?

**Comment by Him-2C** [comment]
@robinweser
I confirm one. I I have tried to upgrade in package and run build my project, it's nothing happen with me.
Better wait for others confirm
