### ISSUE TITLE
Upgrade ua-parser-js to 0.7.23

### ISSUE THREAD

**Issue by alanhogan** [robinweser/fela#840]
**Type**: Bug 

| Packages | Version |
| -------- | ------- |
| fela     | 11.0.0   |
| react-fela     | 11.0.0   |

-------------------
#### Description
A regex DOS attack exists for ua-parser-js 0.7.22. Consider requiring 0.7.23 for fela-bindings, which is used by react-fela and possibly other packages.

Not so much as a bug as a security advisory
https://snyk.io/vuln/SNYK-JS-UAPARSERJS-1023599

**Comment by robinweser** [comment]
Would you be up to send a quick PR updating that? Or which package uses it? Since we don't require that manually, it must be some transitive dependency.

**Comment by robinweser** [comment]
We are using 0.7.2.3 in our .lock now. Should be automatically updated that way as it's a peerDependency of `fbjs`.
