### ISSUE TITLE
Preact useFela hook is missing

### ISSUE THREAD

**Issue by pontakornth** [robinweser/fela#843]
**Type**: Feature

| Packages | Version |
| -------- | ------- |
| fela     | 6.0.x   |

-------------------
#### Description
I try to use `useFela` hook in preact-fela but turn outs that it's missing.

#### Proposal
I think it might be possible to copy content of `react-fela` hook and change the call to use Preact variant. 

Edit 1: I think the documentation should be updated as well since Preact hook is available now.

**Comment by winston0410** [comment]
Want this hook as well!

**Comment by pontakornth** [comment]
> Want this hook as well!

I opened a PR for this hook. I think using same code as React counterpart should be fine.

**Comment by robinweser** [comment]
I'm going to review and merge this asap, thanks for the PR!
