### ISSUE TITLE
Broken types for the composition api

### ISSUE THREAD

**Issue by hedwiggggg** [robinweser/fela#845]
**Type**: Bug

| Packages | Version |
| -------- | ------- |
| react-fela | 11.5.1 |

-------------------
#### Description
The composition api seems to be broken in typescript due to broken .d.ts.
The [docs](https://fela.js.org/docs/latest/guides/usage-with-react#composition) state that composition is possible by giving the css function an array of rules.

```typescript
const styleA = { padding: 10 };
const styleB = { fontSize: 16 };

function Test() {
  const { css } = useFela();

  return (
    <div className={css([styleA, styleB])} />
  )
}
```

This should be possible, but typescript is reporting:

```
error TS2345: Argument of type '({ padding: number; } | { fontSize: number; })[]' is not assignable to parameter of type 'CssFelaStyle<{}, {}>'.
  Type '({ padding: number; } | { fontSize: number; })[]' is not assignable to type 'IStyle'.
    Types of property 'filter' are incompatible.
      Type '{ <S extends { padding: number; } | { fontSize: number; }>(predicate: (value: { padding: number; } | { fontSize: number; }, index: number, array: ({ padding: number; } | { fontSize: number; })[]) => value is S, thisArg?: any): S[]; (predicate: (value: { ...; } | { ...; }, index: number, array: ({ ...; } | { ...; })[...' is not assignable to type 'string'.

16     <div className={css([styleA, styleB])} />
                           ~~~~~~~~~~~~~~~~
```

#### Steps to reproduce

1. Create a component using the comosition api

#### Expected Behavior
Code should compile without any error

#### Actual Behavior
Code throws the stated error

The problem I found is, that the definition file is using two different Style types. What I mean is:

```typescript
type CssFelaStyle<T, P> = IStyle | StyleFunction<T, P>
type FelaStyle<T, P = {}> = IStyle | StyleFunction<T, P> | Array<StyleFunction<T, P> | IStyle>
```

They are nearly identical, except the `Array<StyleFunction<T, P> | IStyle>`, which is missing in the `CssFelaStyle` type.
Is there a reason for that? If not i can make a pull request, swapping `CssFelaStyle` with `FelaStyle`.

So

```typescript
export type CssFelaStyle<T, P> = IStyle | StyleFunction<T, P>
export type CssFunction<T, P> = (...style: CssFelaStyle<T, P>[]) => string

export interface FelaHookProps<T, P> {
  css: CssFunction<T, P>,
  theme: T,
  renderer: IRenderer,
}

export function useFela<T = {}, P = {}>(props?: P): FelaHookProps<T, P>
```

would become

```typescript
export type CssFunction<T, P> = (...style: FelaStyle<T, P>[]) => string

export interface FelaHookProps<T, P> {
  css: CssFunction<T, P>,
  theme: T,
  renderer: IRenderer,
}

export function useFela<T = {}, P = {}>(props?: P): FelaHookProps<T, P>
```

**Comment by hedwiggggg** [comment]
Created two pull requests, one for `react-fela` and one for `preact-fela`.

**Comment by hedwiggggg** [comment]
Well, the real problem here ist, that the docs are wrong.
Because I realize now, that

```typescript
export type CssFunction<T, P> = (...style: CssFelaStyle<T, P>[]) => string
```

means composition by calling `css(styleA, styleB)` is possible.

So I guess instead of the types, the docs should be fixed?
Or both? Because passing an array of rules also works.

**Comment by robinweser** [comment]
Yeah both ways work. Arrays work to simplify extending styles via props while the arguments list is the more "base" solution here. Anything we need to change to support both or is everything covered with the PRs I just merged in?

**Comment by hedwiggggg** [comment]
Should be, now it's possbile to do the following:

```typescript
const exampleRule1 = { color: 'black' };
const exampleRule2 = { color: 'red' };
const exampleRule3 = { color: 'green' };
const exampleRule4 = { color: 'blue' };

const demo = () => (
  <code className={css(exampleRule1)}>
    {`should be ${exampleRule1.color}`}
  </code>
  
  <code className={css(exampleRule1, exampleRule2)}>
    {`should be ${exampleRule2.color}`}
  </code>
  
  <code className={css([exampleRule1])}>
    {`should be ${exampleRule1.color}`}
  </code>
  
  <code className={css([exampleRule1, exampleRule2])}>
    {`should be ${exampleRule2.color}`}
  </code>
  
  <code className={css([exampleRule1, exampleRule2], exampleRule3)}>
    {`should be ${exampleRule3.color}`}
  </code>
  
  <code className={css(exampleRule3, [exampleRule1, exampleRule2])}>
    {`should be ${exampleRule2.color}`}
  </code>
  
  <code className={css([exampleRule1, exampleRule2], [exampleRule3, exampleRule4])}>
    {`should be ${exampleRule4.color}`}
  </code>
);
```

which renders to 
![Bildschirmfoto von 2021-01-19 11-24-05](https://user-images.githubusercontent.com/42947316/105021485-e0c3b700-5a48-11eb-975b-6f2ae531933e.png)

**Comment by robinweser** [comment]
K great! Ill close this one then
