### ISSUE TITLE
Broken types for the plugin api

### ISSUE THREAD

**Issue by hedwiggggg** [robinweser/fela#848]
**Type**: Bug

| Packages | Version |
| -------- | ------- |
| fela     | 11.5.1   |

-------------------
#### Description
Creating a typed plugin with the `TPlugin` type is missing the properties `type`, `renderer` and `props` as declared [here](https://fela.js.org/docs/latest/advanced/plugins#parameter).

#### Steps to reproduce

1. create an new plugin with typescript
2. type your plugin with the `TPlugin` type

#### Expected Behavior
```typescript
import isCSSShorthand from 'is-css-shorthand';

import type { TPlugin, IStyle } from 'fela';

const isStyle = (
  (val: unknown): val is IStyle => (
    val != null
      && typeof val === 'object'
      && Array.isArray(val) === false
  )
);

const checkCSSShorthand: TPlugin = (
  (style: IStyle, type): IStyle => {
    if (type !== 'RULE') return style;

    const $styleEntries = Object.entries(style);

    for (let i = 0; i < $styleEntries.length; i += 1) {
      const [prop, value] = $styleEntries[i];

      if (isCSSShorthand(prop)) {
        // eslint-disable-next-line no-console
        console.debug('css shorthand found', prop, value);
      }

      if (isStyle(value)) {
        checkCSSShorthand(value, type);
      }
    }

    return style;
  }
);
```

#### Actual Behavior
`Type '(style: IStyle, type: any) => IStyle' is not assignable to type 'TPlugin'.ts(2322)`

**Comment by hedwiggggg** [comment]
The most obvious solution would be to extends the type to the following:

```typescript
  type RenderType = 'RULE' | 'KEYFRAME' | 'FONT' | 'STATIC';

  //http://fela.js.org/docs/advanced/Plugins.html
  type TPlugin<T = {}> = (
    (
      style: IStyle,
      type: RenderType,
      renderer: IRenderer,
      props: T,
    ) => IStyle
  );
```

But this would introduce breaking changes, because it would lead to the following error:

```typescript
const checkCSSShorthand: TPlugin = (
  (style: IStyle, type): IStyle => {
    if (type !== 'RULE') return style;

    const $styleEntries = Object.entries(style);

    for (let i = 0; i < $styleEntries.length; i += 1) {
      const [prop, value] = $styleEntries[i];

      if (isCSSShorthand(prop)) {
        // eslint-disable-next-line no-console
        console.debug('css shorthand found', prop, value);
      }

      if (isStyle(value)) {
        // Expected 4 arguments, but got 2.ts(2554)
        // index.d.ts(23, 7): An argument for 'renderer' was not provided.
        checkCSSShorthand(value, type);
      }
    }

    return style;
  }
);
```

So my suggestion would be, to make the other properties optional.

```typescript
  type RenderType = 'RULE' | 'KEYFRAME' | 'FONT' | 'STATIC';

  //http://fela.js.org/docs/advanced/Plugins.html
  type TPlugin<T = {}> = (
    (
      style: IStyle,
      type?: RenderType,
      renderer?: IRenderer,
      props?: T,
    ) => IStyle
  );
```

That's not quite right, because the other properties are always defined, but it would not introduce breaking changes for peoples currently using this type.

**Comment by hedwiggggg** [comment]
Could you drop your thoughts on this @robinweser? Then I can create a pull request.

**Comment by robinweser** [comment]
I feel like the second one is the more clever solution right? So I'd probably want to go with that one.
Would you be open to send a PR to fix it?

**Comment by hedwiggggg** [comment]
Additional thought:

I'm not sure If first option **_really_** introduces a breaking change.
Because you just weren't able to use the other parameters, I you are using typescript.

The only possibilities, to use the other parameters, are the following:

```typescript
const examplePlugin = (
  (style: IStyle, type: string): IStyle => style
) as TPlugin;
```

But then you couldn't use recursive plugin calls, what is quite common.

```typescript
const examplePlugin = (
  (style: IStyle, type: string): IStyle => examplePlugin(style, type) // Expected 1 arguments, but got 2.ts(2554)
) as TPlugin;
```

So If you are using the other parameters the only solution would be:

```typescript
const examplePlugin = (
  (style: IStyle, type: string): IStyle => examplePlugin(style, type) // ok
);

const exampleConfig: IConfig = {
  plugins: [examplePlugin as TPlugin] // ok
};
```

And If you are doing it like this, introducing the fixed type..

```typescript
type TRenderType = 'RULE' | 'KEYFRAME' | 'FONT' | 'STATIC';

type TPlugin<T = Record<string, unknown>> = {
  (
    style: IStyle,
    type: TRenderType,
    renderer: IRenderer,
    props: T,
  ): IStyle;
};
```

..wouldn't break the code.

So I guess, I'd go with the first solution. Because It represents the real way, the code is working.

**Comment by hedwiggggg** [comment]
But otherwise, using the first solution would lead to something like this:

```typescript
const examplePlugin: TPlugin = (
  (style, type, ...rest): IStyle => {
    if (type === 'RULE') {
      return examplePlugin(style, type, ...rest);
    }
  }
);
```

**Comment by hedwiggggg** [comment]
Well, need to correct myself there. You don't need to require all the unused types.
Only if you are stricly typing the function to a TPlugin.

This is perfectly valid:

```typescript
type TRenderType = 'RULE' | 'KEYFRAME' | 'FONT' | 'STATIC';

type TPlugin<T = Record<string, unknown>> = {
  (
    style: IStyle,
    type: TRenderType,
    renderer: IRenderer,
    props: T,
  ): IStyle;
};

const exampleConfig: IConfig = {
  plugins: [
    function recursivePluginExample (style: IStyle, rule: TRenderType): IStyle {
      if (rule === 'RULE') return recursivePluginExample(style, 'FONT');
      return style;
    },
  ],
};
```
