### ISSUE TITLE
Update react-fela peer dependency react to support v17

### ISSUE THREAD

**Issue by jaydenseric** [robinweser/fela#853]
**Type**: Bug

| Packages | Version |
| -------- | ------- |
| react-fela | 11.5.2 |

-------------------
#### Description

The `react-fela` package only declares support for `react` v16, and not v17, in peer dependencies:

https://github.com/robinweser/fela/blob/1f360024e2109f55b531817f334d3da402003366/packages/react-fela/package.json#L34

#### Steps to reproduce

With npm v7+:

1. Run `npm install react` to install `react` v17.
2. Run `npm install react-fela`.

#### Expected Behavior

A successful npm installation.

#### Actual Behavior

npm install errors:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: [redacted]@[redacted]
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.3.0" from react-fela@11.5.2
npm ERR! node_modules/react-fela
npm ERR!   react-fela@"*" from the root project
```

It's not an option to downgrade either npm or react (v17 has been out for over 3 months). This is a lot of friction in the first few seconds of trying `fela` :(

**Comment by robinweser** [comment]
Hmm, I've never ever seen issues with peerDependencies at all. It is new to npm? I only use Yarn so I'm not sure. All I get is a warning for unmet peers, but I can still use React 17 just fine. Anyways, will make it a wider range with the next update.

**Comment by KittyGiraudel** [comment]
Handled in #857.
