### ISSUE TITLE
Readme docs links 404

### ISSUE THREAD

**Issue by jaydenseric** [robinweser/fela#854]
**Type**: Bug

| Packages | Version |
| -------- | ------- |
| react-fela | 11.5.2 |

-------------------
#### Description

A documentation link in the `react-fela` readme 404s. Maybe others in other readmes also 404; I haven't checked.

#### Steps to reproduce

1. Go to the `readme.md` of `react-fela` (https://github.com/robinweser/fela/tree/v11.5.2/packages/react-fela#usage).
2. Click the "Fela Documention - Usage with React." link. Note that `Documention` is actually a spelling error.

#### Expected Behavior

Documentation links do not 404, or contain spelling errors.

#### Actual Behavior

Documentation links 404, and contain spelling errors.

**Comment by robinweser** [comment]
Good catch, we recently moved to a completely new website and those links changed. Haven't checked all sub packages yet. Simply to go https://fela.js.org directly and look into Usage with React, that's all you need to know!

**Comment by robinweser** [comment]
Just quickly fixed the links.
