### ISSUE TITLE
Use fela with ReactDOM.createPortal on a different window

### ISSUE THREAD

**Issue by Deltaxel** [robinweser/fela#858]
**Type**: Feature

| Packages | Version |
| -------- | ------- |
| fela     | 11.5.2  |
| fela-dom | 11.5.2 |
| react-fela | 11.5.2 |
| react | 17.0.1 |
| react-dom | 17.0.1 |

-------------------
#### Description
I created a react component that open a new window and use `ReactDom.createPortal(...)` to render elements on that window. As a result, elements on the new window gets created with proper class names but no style was added to the DOM of that window.
I tried to create a different renderer, use a different `RendererProvider` but this only managed to brake the first window.
It seems that this scenario is not supported yet.

#### Proposal 1

A first proposal would be to add an optional window/document parameter to the `createRenderer` method. The renderer would then use it (when set) to create a new `<style />` element on that new document and would be passed to components via a different `RendererProvider`.

**Code Example**:
```javascript
const mainWindowRenderer = createRenderer();
const subWindow = window.open(...);
const subWindowRenderer = createRenderer({ window: subWindow });

// Main render
render() {
  return (
    <RendererProvider renderer={mainWindowRenderer }>
      ...
    </RendererProvider>
  );
}

// New window component
render() {
  return ReactDOM.createProtal(
    (
      <RendererProvider renderer={subWindowRenderer}>
        {this.props.children}
      </RendererProvider>
    ),
    subWindow.document.body
  );
}

```

#### Proposal 2

A second proposal would be to have a new component `StyleProvider`. The component would be attached to the header of the new window and it would copy the style present on the main window.

**Code Example**
```javascript
React.render(<StyleComponent />, subWindow.document.head);
```

**Comment by robinweser** [comment]
Ah good catch. We only miss the docs on that part. You can actually pass a `targetDocument` prop to the RendererProvider. This would have to be `subWindow.document` in this scenario. Then it should work fine!

I wil close this one for now and create a new issue on documenting the`targetDocument` prop.
