### ISSUE TITLE
Fela doesn’t hydrate CSS custom properties

### ISSUE THREAD

**Issue by KittyGiraudel** [robinweser/fela#860]
**Type**: Bug

| Packages | Version |
| -------- | ------- |
| fela     | 11.5.x   |

-------------------
#### Description

Fela does not appear to hydrate CSS custom properties.

<img width="544" alt="Screenshot 2021-02-11 at 12 14 16" src="https://user-images.githubusercontent.com/76733786/107630963-9b1f9600-6c64-11eb-8dd4-7de4d1c1f480.png">

#### Expected Behavior

CSS custom property declarations should be picked up during hydration instead of causing the same declaration to be regenerated with a different class name, thus causing a rendering mismatch.

#### Actual Behavior

The CSS custom property declarations are not hydrated properly, causing a rendering mismatch.

**Comment by robinweser** [comment]
Fixes with #866
