### ISSUE TITLE
renderToNodeList not exported in react-fela/index.d.ts

### ISSUE THREAD

**Issue by pennyshen** [robinweser/fela#868]
**Type**: Bug / Feature / Infrastructure / Docs / Question

| Packages | Version |
| -------- | ------- |
| react-fela     | 11.4.0  |

-------------------
#### Description
When I do 
```
import {renderToNodeList} from 'react-fela'
```

in my typescript project, typecheck fails and says renderToNodeList is not exported.

I think it's because the export is missing in the typescript interface:
https://github.com/robinweser/fela/blob/master/packages/react-fela/index.d.ts

**Comment by robinweser** [comment]
Feel free to go ahead and quickly add it to the definitions :)
Should be a simple one.
