### ISSUE TITLE
Typescript plugin doesn't extend style definition

### ISSUE THREAD

**Issue by horaklukas** [robinweser/fela#872]
**Type**: Bug

| Packages | Version |
| -------- | ------- |
| fela     | 11.6  |

-------------------
#### Description
Please try to add as much detail as possible.

Hi,

I'm using `fela-plugin-typescript` but it seems that its `d.ts` definition doesn't correctly extends the style definition. Typescript compiler produces error like the one below when I try to use any nested or pseudo selector.

> Type '{ nested: { '& .ant-page-header-heading-title': { alignSelf: string; }; }; }' has no properties in common with type 'IStyle'

Example of my styles

```javascript
import type { TRule } from 'fela';

export const collapse: TRule = () => ({
    nested: {
        '& > .ant-collapse-item > .ant-collapse-header .ant-collapse-arrow': {
            top: 'initial',
        },
    },
});

export const line: TRule = () => ({
    nested: {
        ':hover': {
            textDecoration: 'none',
        },
    }
});
```
Am I doing anything wrong or is it a bug caused by some fela core changes? I made some attempts to fix it and when I replace `IStyleExtension` with `IStyle` in the definition, typescript compiler stops complaining and it seems everything if fine.  

```typescript
declare module "fela" {
    // interface IStyleExtension {
   interface IStyle {
      nested?: INestedSelectors;
    }
```

Should the type be replaced? I can make a PR but first i want to assure myself it's an intended change.

**Comment by robinweser** [comment]
@hedwiggggg Hey Silas! I'm just tagging you here, because you worked on those types a lot. I'm not really into that stuff too much so I can really help out on this one. Any suggestions?

**Comment by hedwiggggg** [comment]
Hmm, weird. Tested your code, is working for me.
Could you provide your `yarn.lock` / `package-lock.json`?
Or even better, reproduce your issue in a codesandbox, for example?

**Comment by hedwiggggg** [comment]
And by the way, with fela 11.6, the fela-plugin-typescript is no longer necessary.
Things like this, should be working fine now:

```typescript

export const line: TRule = () => ({
  width: '100px',

  '&:hover': {
    width: '200px'
  },
});
```

**Comment by hedwiggggg** [comment]
An issue could be, that the types are not merging correctly, have you set up the fela-plugin-typescript correctly?

```typescript
import { createRenderer } from 'fela';
import typescript from 'fela-plugin-typescript';

const renderer = createRenderer({
  plugins: [ typescript() ]
});
```

That should load `fela-plugin-typescript` and merge the `nested` property in `IStyleExtension`.

**Comment by horaklukas** [comment]
> An issue could be, that the types are not merging correctly, have you set up the fela-plugin-typescript correctly?
> 
> ```ts
> import { createRenderer } from 'fela';
> import typescript from 'fela-plugin-typescript';
> 
> const renderer = createRenderer({
>   plugins: [ typescript() ]
> });
> ```
> 
> That should load `fela-plugin-typescript` and merge the `nested` property in `IStyleExtension`.

Yes, I setup them correctly. After all your notes I tested it again and have to apologize, because I posted a wrong version. I'm currently working on more projects and the one where it wasn't working used Fela 11.5 but had the plugin in version 11.6. After upgrade to 11.6, it works (as you adviced me) without the need of having `fela-plugin-typescript` so it's even better 👍

Thank's a lot for your help, closing as an invalid, having versions in sync is the solution.
