### ISSUE TITLE
Missing changelog for 11.5.x & 11.6.x

### ISSUE THREAD

**Issue by andreipfeiffer** [robinweser/fela#878]
**Type**: Docs

| Packages | Version |
| -------- | ------- |
| fela     | 11.5.x  |
| fela     | 11.6.x  |

-------------------
#### Description
The CHANGELOG file is missing entries for the latest 2 minor versions: `11.5` and `11.6`

**Comment by robinweser** [comment]
Whops, I forgot to update the Changelog disclaimer. We moved it over to Releases directly: https://github.com/robinweser/fela/releases

**Comment by andreipfeiffer** [comment]
Got it, thanks Robin, I'll close this :)
