### ISSUE TITLE
Rehydration of `&` selectors 

### ISSUE THREAD

**Issue by jancama2** [robinweser/fela#885]
**Type**: Bug

| Packages | Version |
| -------- | ------- |
| fela     | 11.6.0  |

-------------------
#### Description
In our app we are using a lot of `&` selectors, mostly because of used OSS libraries. I've recently enabled SSR and realized that those selectors are badly hydrated. The problem seem to be only with `&` selectors.

#### Steps to reproduce

Let say I have this rule: 
``` javascript
const rule = () => ({
    paddingBottom: 0,
   '&.rc-tooltip.rc-tooltip-placement-topRight': {
        paddingBottom: 0,
    },
   '&.rc-tooltip > .rc-tooltip-content > .rc-tooltip-arrow': {
         display: 'none',
    },
})
```

After rendering on client without server and hydration this results into given cache:
``` javascript
{
    '.rc-tooltip > .rc-tooltip-content > .rc-tooltip-arrowdisplaynone': {
       className: 'ju',
       declaration: 'display:none'
       media: '',
       pseudo: '.rc-tooltip > .rc-tooltip-content > .rc-tooltip-arrow',
       selector: '.ju.rc-tooltip > .rc-tooltip-content > .rc-tooltip-arrow',
       support: '',
       type: 'RULE',
     },
    '.rc-tooltip.rc-tooltip-placement-topRightpaddingBottom0': {
       className: 'ky',
       declaration: 'paddingBottom:0'
       media: '',
       pseudo: '.rc-tooltip.rc-tooltip-placement-topRight',
       selector: '.ky.rc-tooltip.rc-tooltip-placement-topRight',
       support: '',
       type: 'RULE',
     },
     'paddingBottom0': {
       className: 'co',
       declaration: 'paddingBottom:0'
       media: '',
       pseudo: '',
       selector: '',
       support: '',
       type: 'RULE',
     },
}
```

When the same rule is rendered on the server and hydrated, I would expect the same result, but the result is different:

``` javascript
{
   ' > .rc-tooltip-content > .rc-tooltip-arrowdisplaynone': {
       className: 'gg'
       declaration: 'display:none',
       media: '',
       pseudo: ' > .rc-tooltip-content > .rc-tooltip-arrow',
       selector: '.gg > .rc-tooltip-content > .rc-tooltip-arrow',
       support: '',
       type: 'RULE'
   },
   'paddingBottom0': {
       className: 'ho'
       declaration: 'padding-bottom:0'
       media: ''
       pseudo: ''
       selector: '.ho'
       support: ''
       type: 'RULE'
}
```

As you can see, the key for `&.rc-tooltip.rc-tooltip-placement-topRight` is not in the cache at all and the key for `&.rc-tooltip > .rc-tooltip-content > .rc-tooltip-arrow` has `.rc-tooltip` stripped.

I did some debugging and found out that `rehydrateRules` of `fela-dom` is not working correctly. 

As you can see, there are some weird things happening when parsing declarations in `rehydrateRules`:

```
declaration: '.ag{padding-bottom:0}', 'ag', undefined, undefined, 'padding-bottom', '0', index: 714, input: '.a{position:fixed}.b{top:0}.c{z-index:6000}.d{widt…lor:#1A1D29}.qp:focus-visible{outline-offset:1px}', groups: undefined
declarationReference: 'paddingBottom0'
rule: className: "ag", declaration: "padding-bottom:0", media: "", pseudo: "", selector: ".ag", support: "", type: "RULE"
```

```
declaration: '.ho.rc-tooltip.rc-tooltip-placement-rightBottom{padding-bottom:0}', 'ho', '.rc-tooltip-placement-rightBottom', undefined, 'padding-bottom', '0', index: 6135, input: '.a{position:fixed}.b{top:0}.c{z-index:6000}.d{widt…lor:#1A1D29}.qp:focus-visible{outline-offset:1px}', groups: undefined
declarationReference: 'paddingBottom0'
rule: className: "ho", declaration: "padding-bottom:0", media: "", pseudo: "", selector: ".ho", support: "", type: "RULE"
```

```
declaration: '.gg.rc-tooltip > .rc-tooltip-content > .rc-tooltip-arrow{display:none}', 'gg', '.rc-tooltip', ' > .rc-tooltip-content > .rc-tooltip-arrow', 'display', 'none', index: 3912, input: '.a{position:fixed}.b{top:0}.c{z-index:6000}.d{widt…lor:#1A1D29}.qp:focus-visible{outline-offset:1px}', groups: undefined,
declarationReference: ' > .rc-tooltip-content > .rc-tooltip-arrowdisplaynone'
rule: className: "gg", declaration: "display:none", media: "", pseudo: " > .rc-tooltip-content > .rc-tooltip-arrow", selector: ".gg > .rc-tooltip-content > .rc-tooltip-arrow", support: "", type: "RULE"
```
As you can see, for both `paddingBottom: 0` and `'&.rc-tooltip.rc-tooltip-placement-topRight': { paddingBottom: 0 }` the same `declarationReference` is generated only with a different className and in the cache the rule of the latter one rewrites the cache entry for the first one and doesn't generate an entry for itself. 

There seems to be some problem with the regex to parse the css. It strips `&.rc-tooltip` which results even in the weird cache key `' > .rc-tooltip-content > .rc-tooltip-arrowdisplaynone'`

#### Summary

As mentioned in the previous section, the hydration actually generates a different cache and the problem seems to be with `&.whathever` notation, which I'm not really sure is correct for fela, but we use it quite a lot. I managed to track the problem to `DECL_REGEX` which might be parsing the css badly.

I would expect the cache after hydration from the server to look the same as the cache of the client only version.

**Comment by jancama2** [comment]
I can even provide some minimal demo, but it is pretty straighforward:

## SSR

#### Server
``` javascript
const renderer = createRenderer()
renderer.renderRule(() => ({
    paddingBottom: 0,
   '&.rc-tooltip.rc-tooltip-placement-topRight': {
        paddingBottom: 0,
    },
   '&.rc-tooltip > .rc-tooltip-content > .rc-tooltip-arrow': {
         display: 'none',
    },
}))

const markup = renderToMarkup(renderer)

console.log(renderer.cache)
```

### Client
```javascript
const renderer = createRenderer();

rehydrate(renderer)

// The cache is differet from the server one
console.log(renderer.cache)
```

## Client only
```javascript
const renderer = createRenderer();

render(renderer)

renderer.renderRule(() => ({
    paddingBottom: 0,
   '&.rc-tooltip.rc-tooltip-placement-topRight': {
        paddingBottom: 0,
    },
   '&.rc-tooltip > .rc-tooltip-content > .rc-tooltip-arrow': {
         display: 'none',
    },
}))

// The cache is same as the SSR server one
console.log(renderer.cache)
```

**Comment by robinweser** [comment]
Heyhey!

Sorry for the late response. I have seen it and already identified the issue.
I'll try to replicate it within my tests and publish a fix with 11.7.1 as soon as possible!

**Comment by robinweser** [comment]
@jancama2 I'm about to release a `12.0.0-rc.1` version which includes a fix for this next to a lot of performance improvements. Could you try that out? In ~1h as of writing this.

Here's the only change you might have to do to your configuration (unless you use the web preset anyways): https://fela-git-fela-12-robinweser.vercel.app/docs/latest/extra/migration#12.0.0

**Comment by robinweser** [comment]
If we run into issues with v12, I can as well push this fix to 11.7.1 first, but if 12 works anyways, I might prefer releasing 12 directly next week.

**Comment by jancama2** [comment]
I tried it and on the first sight it looks the issue is solved, I have some problem with `fallbackvalue` plugin tho. Even though I've updated the order, it renders an empty declaration.

```
    felaPluginExtend(),
    felaPluginEmbedded(),
    felaPluginNamedKeys(({ theme }) => ({
        isMobileSmall: `@media (max-width: ${theme.breakpoints.s - 1}px)`,
        isMobile: `@media (max-width: ${theme.breakpoints.lg - 1}px)`,
        isTablet: `@media (min-width: ${theme.breakpoints.md}px)`,
        isDesktop: `@media (min-width: ${theme.breakpoints.lg}px)`,
        supportsGrid: '@supports (display: grid)',
        notSupportsGrid: '@supports not (display: grid)',
    })),
    felaPluginUnit(defaultUnit, {
        fontSize: 'rem',
        lineHeight: 'em',
    }),
    felaPluginPrefixer(),
    felaPluginPlaceholderPrefixer(),
    felaPluginFallbackValue(),
```

See the empty `.vr` class.

<img width="322" alt="Snímek obrazovky 2022-02-18 v 15 21 35" src="https://user-images.githubusercontent.com/3720335/154699948-b0319362-96aa-401c-914c-6985dc39cba6.png">

**Comment by robinweser** [comment]
What should that class be instead?

**Comment by jancama2** [comment]
Sorry for not adding any more info, I've just tried it on Friday quickly and ran into the issue, will try to create an example ASAP :).

**Comment by jancama2** [comment]
https://codesandbox.io/s/strange-wilbur-9nm3k9 here is the sandbox. 
Note that removing the `prefixerPlugin` make the `fallbackPlugin` work correctly. Other interesting thing I noticed is that adding the `monolithic` enhancer fixes the problem.

**Comment by robinweser** [comment]
Aha! I think I found the issue. The actual correct order is:
- unit
- fallback-value
- prefixer

The monolithic plugin might solve that since it doesn't use the optimised plugins at all.
But I wouldn't recommend it for production...

**Comment by jancama2** [comment]
Tried and looks like everything works just fine 🎉

**Comment by robinweser** [comment]
Awesome! A final RC is going out tomorrow which again brings a couple of nice performance improvements.

And yeah, since browsers fixed editing styles that are injected with `insertRule`, I wouldn't recommend monolithic at all.
The only place where I actually like it, is when doing component snapshot tests using [jest-react-fela](https://fela.js.org/docs/latest/api/jest-react-fela/createSnapshot)
