### ISSUE TITLE
Rules are mixing between components when we switch between pages.

### ISSUE THREAD

**Issue by PrashantPermi** [robinweser/fela#893]
**Type**: Bug

| Packages | Version |
| -------- | ------- |
| fela     | 12.0.2  |
| next     | 12.0.10  |
| react     | 17.0.2  |
| react-dom     | 17.0.2  |
| react-fela     | 12.0.2  |

---

#### Steps to reproduce

https://codesandbox.io/s/nextjs-forked-qkcfwc?file=/pages/_app.tsx

1. Click on `Go to test page link`
![image](https://user-images.githubusercontent.com/7992737/155455569-f469b428-a997-4a7a-9d2c-fda94533158f.png)

2. Now, if we look at the Button component, I am passing background prop as `blue`. But somehow the its taking red color.
![image](https://user-images.githubusercontent.com/7992737/155455863-a7a9f1cd-e413-43e4-82e5-04d8166ca685.png)

![Screenshot 2022-02-24 at 9 39 55 AM](https://user-images.githubusercontent.com/7992737/155456485-28147b00-5fb2-4fa4-834e-833620253ca9.png)

Expected Behaviour:
Should not override the styles.

**Comment by robinweser** [comment]
Hey!

I checked your example and it seems that you forgot to pass the renderer from the App component to the FelaRenderer in `_app.js`. Here's a fixed version: https://codesandbox.io/s/nextjs-forked-83it1f?file=/pages/_document.tsx
