### ISSUE TITLE
Typescript interface for renderer configuration (IConfig) misses some options

### ISSUE THREAD

**Issue by AvalonCV** [robinweser/fela#905]
**Type**: Feature

| Packages | Version |
| -------- | ------- |
| fela     | 12.x.x  |

---

#### Description

Hello,

the documentation for "Renderer Configuration" https://fela.js.org/docs/latest/advanced/renderer-configuration includes the following options
* optimizeCaching
* styleNodeAttributes
* propertyPriority

that are currently not part of the IConfig interface in fela/index.d.ts

#### Proposal

Add the missing options to the interface - maybe like:

**Code Example**:

```javascript
  interface IConfig {
    ...
    optimizeCaching?: boolean
    styleNodeAttributes?: { [key: string]: string }
    propertyPriority?: : { [key: string]: number}
  }
```
?

Thanks and have a nice day :)

**Comment by marwan38** [comment]
@robinweser his PR is up
