### ISSUE TITLE
Fail to set backgroundImage fallback value

### ISSUE THREAD

**Issue by MincoKe** [robinweser/fela#914]
**Type**: Bug

| Packages | Version |
| -------- | ------- |
| fela     | 12.2.1  |

---

#### Description

set backgroundImage fallback, but it didn't work

#### Steps to reproduce
1. add code 
```
backgroundImage: [
                        'url("/assets/site/home-bg-03.jpg")',
                        `image-set(
                            url("/assets/site/home-bg-03.avif") type("image/avif"),
                            url("/assets/site/home-bg-03.jpg") type("image/jpeg")
                        )`,
                    ]
```
2. apply fallback plugin
```javascript
const renderer = createRenderer({
    plugins: [fallbackValue()],
  });
  ```

#### Expected Behavior

```javascript
background-image: 'url("/assets/site/home-bg-03.jpg"), image-set(url("/assets/site/home-bg-03.avif") type("image/avif"),url("/assets/site/home-bg-03.jpg") type("image/jpeg"))'
```

#### Actual Behavior

```javascript
background-image: image-set(url("/assets/site/home-bg-02.avif") 1x type("image/avif"), url("/assets/site/home-bg-02.jpg") 1x type("image/jpeg"))
```

**Comment by robinweser** [comment]
Works for me: https://codesandbox.io/s/fela-fallback-value-rn54p5

Make sure to put the fallback last, so that it's not overwritten.
Also fallback values work different than what you're actual behaviour looks like. Instead of joining the values with a `,` it creates multiple CSS properties e.g.
```css
background-image: image-set(
  url("/assets/site/home-bg-03.avif") type("image/avif"),
  url("/assets/site/home-bg-03.jpg") type("image/jpeg")
);
background-image: url("/assets/site/home-bg-03.jpg")
```

**Comment by MincoKe** [comment]
https://codesandbox.io/s/busy-banzai-2yvqyd

could you check this one?
still generated ``` background-image: url(/assets/site/home-bg-03.jpg); ```

use following code will generate the correct css
```
renderer.renderRule(swiperSlideContainerRule);
const output = renderToString(renderer);
  ```

**Comment by robinweser** [comment]
Whoops sorry, I was wrong regarding the order. You actually put the fallback first of course, as CSS is applied top to bottom.
You will still have the fallback rendered to CSS, but (if the browser supports it) the `image-set` will be used that way.
